### ISSUE TITLE
Why can I see this operation button when I am not logged in?

### ISSUE THREAD

**Issue by huasio** [migratetoflarum/fake-data#16]
Normally speaking, we, as webmasters, certainly don’t want users to know about false data. However, at present, users can see this button and infer that the sites are all virtual popularity.

![image](https://user-images.githubusercontent.com/23445537/139533692-9cd95260-fa60-4261-98f2-6257809e9dab.png)

**Comment by clarkwinkelmann** [comment]
There is currently no check in the frontend to show/hide the button, so it's always visible.

This generally isn't an issue since the extension is not supposed to be installed on production websites.

I'll try to hide it for non-admins in a future version.

**Comment by huasio** [comment]
> There is currently no check in the frontend to show/hide the button, so it's always visible.
> 
> This generally isn't an issue since the extension is not supposed to be installed on production websites.
> 
> I'll try to hide it for non-admins in a future version.

I think the plug-in that may be used in production, I have used it now, and it is very easy to use. Can I suggest some suggestions? You can add permissions to the plug-in so that the front-end will not have this display problem.

**Comment by clarkwinkelmann** [comment]
Button is now hidden for non-admins in version 1.2.0
